
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 17 04:11:22 CET 2014
//----------------------------------------------------

package gantt;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int DATE = 10;
  public static final int DESCRIBE = 4;
  public static final int EOLN = 2;
  public static final int CREATE_T = 3;
  public static final int DESCRIPTION = 11;
  public static final int LABEL = 9;
  public static final int FINISH = 6;
  public static final int EOF = 0;
  public static final int LABELLED = 7;
  public static final int error = 1;
  public static final int START = 5;
  public static final int NAME = 8;
}

