
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 12 10:33:33 CET 2013
//----------------------------------------------------

package gantt;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int UPLUS = 12;
  public static final int DIVIDE = 6;
  public static final int UMINUS = 13;
  public static final int NUMBER = 10;
  public static final int EOLN = 9;
  public static final int EQUAL = 2;
  public static final int PLUS = 3;
  public static final int EOF = 0;
  public static final int ID = 11;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 5;
  public static final int LPAREN = 7;
}

